### ISSUE TITLE
[Help wanted] Usage with ngrok

### ISSUE THREAD

**Issue by Satont** [dnsge/twitch-eventsub-framework#5]
Are you familar with ngrok?

I have a problem with that tunnel, my events in dev mode is repeated (retried) by twitch.

I'm used helper for getting tunnel for eventsub client
```go
func GetAppTunnel(ctx context.Context, cfg *config.Config) (net.Listener, error) {
	if cfg.AppEnv != "production" {
		tun, err := ngrok.Listen(ctx,
			ngrok_config.HTTPEndpoint(),
		)
		if err != nil {
			return nil, err
		}

		return tun, nil
	} else {
		tun, err := net.Listen("tcp", ":3003")
		if err != nil {
			return nil, err
		}
		return tun, nil
	}
}
```

After that using it like:
```go
	appTun, err := helpers.GetAppTunnel(appCtx, cfg)
	if err != nil {
		panic(err)
	}

	appAddr := lo.
		If(cfg.AppEnv != "production", appTun.Addr().String()).
		Else(fmt.Sprintf("eventsub.%s", cfg.HostName))

	eventSubHandler := handler.NewHandler(services)
		go func() {
                         // manager here is *eventsub_framework.SubHandler
			if err := http.Serve(appTun, eventSubHandler.Manager); err != nil {
				panic(err)
			}
		}()

	fmt.Println("Listening on %s", appAddr)
```

**Comment by dnsge** [comment]
I am familiar with ngrok's command line interface but not familiar with the Go library. However, the code you posted makes sense and looks like it should be no different from receiving HTTP requests on the local port. 

Some thoughts:

1. My understanding is that ngrok has a web interface which lets you inspect requests and responses that go through your tunnel. If you look at this interface, are you seeing the notification requests from Twitch go through? If so, do you also see a response? If not, maybe put some wrapper code around the `eventSubHandler.Manager` handler to intercept and log what's happening, e.g. implementing an `http.ResponseWriter` that logs the calls to `Write` and `WriteHeader`.

2. If you run ngrok via the command line, e.g. forward your ngrok domain to port 3003 or what have you, do you still get retry issues? I don't expect this to make a difference given the `GetAppTunnel` seems perfectly reasonable.

3. My theory behind why #2 was needed was this: your proxy must not be sending the HTTP response from the server over the proxy because it is still waiting for more of the response. i.e., setting `Content-Length: 0` and responding with a 204 would indicate to the proxy that the response is finished. I use my own tunnel system (which I do NOT advise you use, it's really sketchy and not production-ready) https://github.com/dnsge/leap and I have it force the connection to close per-request: https://github.com/dnsge/leap/blob/0ed301834c87bf5826bc66f0711f11a9e3280e2a/server/proxy.go#L16 so it would make sense that I don't experience the issue with leap while you do with some other tool.

4. I'm assuming that your problem of retrying events means retrying notification events. If the retries are occurring on subscription verification, perhaps a patch like so could fix the issue? (similar to #2's fix)

```patch
diff --git a/handler.go b/handler.go
index d1ad0da..30a6476 100644
--- a/handler.go
+++ b/handler.go
@@ -6,6 +6,7 @@ import (
 	"github.com/mozillazg/go-httpheader"
 	"io"
 	"net/http"
+	"strconv"
 )

 const (
@@ -175,6 +176,7 @@ func (s *SubHandler) handleVerification(w http.ResponseWriter, bodyBytes []byte,

 	if s.VerifyChallenge == nil || s.VerifyChallenge(headers, &data) {
 		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
+		w.Header().Set("Content-Length", strconv.Itoa(len(data.Challenge)))
 		w.WriteHeader(http.StatusOK)
 		_, _ = w.Write([]byte(data.Challenge))
 	} else {
```

**Comment by Satont** [comment]
Verification seems to be ok, it happens only for notifications.

Opened ngrok via cli with web interface, thats what i see:

Request:
```http
POST / HTTP/1.1
Host: 0e2b-51-195-203-226.eu.ngrok.io
User-Agent: Go-http-client/1.1
Content-Length: 581
Accept-Encoding: gzip
Content-Type: application/json

Twitch-Eventsub-Message-Id: I4_kvZKlk5hTNo4HYhl0DMvaOWun_CiJcKvqUa65a9Y=
Twitch-Eventsub-Message-Retry: 3
Twitch-Eventsub-Message-Signature: sha256=2049f3eb264a899b34576ae4e4caaa2ce72a3615751c3e42f30fe0077ac47608
Twitch-Eventsub-Message-Timestamp: 2023-03-23T23:50:37.728111013Z
Twitch-Eventsub-Message-Type: notification
Twitch-Eventsub-Subscription-Is-Batching-Enabled: false
Twitch-Eventsub-Subscription-Type: channel.follow
Twitch-Eventsub-Subscription-Version: 2
X-Forwarded-For: 54.184.54.118
X-Forwarded-Proto: https


{"subscription":{"id":"75e46cc8-92d4-4e0a-bbb6-dccc3dfb43f5","status":"enabled","type":"channel.follow","version":"2","condition":{"broadcaster_user_id":"869882828","moderator_user_id":"869882828"},"transport":{"method":"webhook","callback":"https://0e2b-51-195-203-226.eu.ngrok.io"},"created_at":"2023-03-23T23:49:58.691670613Z","cost":0},"event":{"user_id":"876987810","user_login":"eventpupa","user_name":"EventPupa","broadcaster_user_id":"869882828","broadcaster_user_login":"sadisnamenya","broadcaster_user_name":"SadisNaMenya","followed_at":"2023-03-23T23:50:37.728103715Z"}}
```

Response:
```http
HTTP/1.1 204 No Content
Date: Thu, 23 Mar 2023 23:51:49 GMT
```

**Comment by Satont** [comment]
What is actually helps me, it's change `writeEmpty` to 
```go
func writeEmpty(w http.ResponseWriter) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("Ok"))
}
```

I'm not sure about that, maybe twitch somehow stricky about those responds, or it stupid coincidence...

**Comment by dnsge** [comment]
@Satont Could you check out #6? If it fixes your problem I'll go ahead and merge it in. 

As for your comment on dnsge/twitch-eventsub-bindings#1, I already made a new release bumping the `twitch-eventsub-bindings` version but I'll make another when (if) #6 gets merged. I have no clue if you can mix dependency versions so I'll just make a new release on this module whenever I update the bindings.

**Comment by Satont** [comment]
Didn't I write in a previous comment that I changed it and it worked for me? But yes, it still needs to be tried again to be sure.

**Comment by Satont** [comment]
Yep, it's working just fine, no retries.
